# .streamlit/config.toml

[theme]
primaryColor = "#4E79A7"              
backgroundColor = "#F8F9FA"           
secondaryBackgroundColor = "#FFFFFF"  
textColor = "#212529"                   
font = "sans serif"                   


[server]
headless = true

[client]
showSidebarNavigation = true